/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface GethererInterface extends ethers.utils.Interface {
  functions: {
    "multiswap(address,address[],uint256[])": FunctionFragment;
    "swap(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "multiswap",
    values: [string, string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "multiswap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;

  events: {};
}

export class Getherer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: GethererInterface;

  functions: {
    multiswap(
      token: string,
      users: string[],
      amountsIn: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "multiswap(address,address[],uint256[])"(
      token: string,
      users: string[],
      amountsIn: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    swap(
      token: string,
      user: string,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "swap(address,address,uint256)"(
      token: string,
      user: string,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  multiswap(
    token: string,
    users: string[],
    amountsIn: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "multiswap(address,address[],uint256[])"(
    token: string,
    users: string[],
    amountsIn: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  swap(
    token: string,
    user: string,
    amountIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "swap(address,address,uint256)"(
    token: string,
    user: string,
    amountIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    multiswap(
      token: string,
      users: string[],
      amountsIn: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "multiswap(address,address[],uint256[])"(
      token: string,
      users: string[],
      amountsIn: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    swap(
      token: string,
      user: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "swap(address,address,uint256)"(
      token: string,
      user: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    multiswap(
      token: string,
      users: string[],
      amountsIn: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "multiswap(address,address[],uint256[])"(
      token: string,
      users: string[],
      amountsIn: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    swap(
      token: string,
      user: string,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "swap(address,address,uint256)"(
      token: string,
      user: string,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    multiswap(
      token: string,
      users: string[],
      amountsIn: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "multiswap(address,address[],uint256[])"(
      token: string,
      users: string[],
      amountsIn: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    swap(
      token: string,
      user: string,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "swap(address,address,uint256)"(
      token: string,
      user: string,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
